name       : haskell-mtl
version    : 2.2.1
release    : 4
source     :
    - http://hackage.haskell.org/package/mtl-2.2.1/mtl-2.2.1.tar.gz : cae59d79f3a16f8e9f3c9adc1010c7c6cdddc73e8a97ff4305f6439d855c8dc5
license    : BSD-3-Clause
component  : programming.haskell
summary    : Monad classes using functional dependencies, with instances for various
    monad transformers, inspired by the paper Functional Programming with Overloading
    and Higher-Order Polymorphism, by Mark P Jones
description: |
    Monad classes using functional dependencies, with instances for various monad transformers, inspired by the paper Functional Programming with Overloading and Higher-Order Polymorphism, by Mark P Jones
builddeps  :
    - ghc
    - haskell-cabal-install
setup      : |
    sed -i "s|0.4.\*|0.5.\*|" mtl.cabal
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
