name       : haskell-mtl
version    : 2.2.2
release    : 5
source     :
    - https://hackage.haskell.org/package/mtl-2.2.2/mtl-2.2.2.tar.gz : 8803f48a8ed33296c3a3272f448198737a287ec31baa901af09e2118c829bef6
license    : BSD-3-Clause
component  : programming.haskell
summary    : Monad classes using functional dependencies, with instances for various monad transformers, inspired by the paper Functional Programming with Overloading and Higher-Order Polymorphism, by Mark
    P Jones
description: |
    Monad classes using functional dependencies, with instances for various monad transformers, inspired by the paper Functional Programming with Overloading and Higher-Order Polymorphism, by Mark P Jones
builddeps  :
    - ghc
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
