name       : haskell-mtl
version    : 2.2.1
release    : 2
source     :
    - http://hackage.haskell.org/package/mtl-2.2.1/mtl-2.2.1.tar.gz : cae59d79f3a16f8e9f3c9adc1010c7c6cdddc73e8a97ff4305f6439d855c8dc5
license    : BSD-3-Clause
component  : programming
summary    : Monad classes using functional dependencies, with instances for various
    monad transformers, inspired by the paper Functional Programming with Overloading
    and Higher-Order Polymorphism, by Mark P Jones
description: |
    Monad classes using functional dependencies, with instances for various monad transformers, inspired by the paper Functional Programming with Overloading and Higher-Order Polymorphism, by Mark P Jones
builddeps  :
    - ghc
setup      : |
    ghc -threaded Setup
    sed -i "s|0.4.\*|0.5.\*|" mtl.cabal
    ./Setup configure --enable-shared \
                      --prefix=/usr \
                      --docdir="/usr/share/doc/\$compiler/\$pkgid" \
                      --libdir=/usr/lib64 \
                      --libsubdir="\$compiler/\$pkgid" \
                      --datadir=/usr/share \
                      --sysconfdir=/etc
build      : |
    ./Setup build
install    : |
    export GHCV=`readlink /usr/bin/ghc`
    ./Setup copy --destdir=$installdir
    ./Setup register --gen-pkg-config
    install -D -m 00644 mtl-$version.conf $installdir/usr/lib64/$GHCV/package.conf.d/mtl-$version.conf
